using UnityEngine;

namespace SplineMesh;

[ExecuteInEditMode]
[RequireComponent(typeof(Spline))]
public class ExampleGrowingRoot : MonoBehaviour
{
	private GameObject generated;

	private Spline spline;

	private float rate;

	private MeshBender meshBender;

	public Mesh mesh;

	public Material material;

	public Vector3 rotation;

	public Vector3 scale;

	public float startScale = 1f;

	public float DurationInSecond;

	private void OnEnable()
	{
		rate = 0f;
		Init();
	}

	private void OnDisable()
	{
	}

	private void OnValidate()
	{
		Init();
	}

	private void Update()
	{
		EditorUpdate();
	}

	private void EditorUpdate()
	{
		rate += Time.deltaTime / DurationInSecond;
		if (rate > 1f)
		{
			rate -= 1f;
		}
		Contort();
	}

	private void Contort()
	{
		float num = 0f;
		int num2 = 0;
		foreach (SplineNode node in spline.nodes)
		{
			float num3 = num / spline.Length;
			float num4 = startScale * (rate - num3);
			node.Scale = new Vector2(num4, num4);
			if (num2 < spline.curves.Count)
			{
				num += spline.curves[num2++].Length;
			}
		}
		if (generated != null)
		{
			meshBender.SetInterval(spline, 0f, spline.Length * rate);
			meshBender.ComputeIfNeeded();
		}
	}

	private void Init()
	{
		string n = "generated by " + GetType().Name;
		Transform transform = base.transform.Find(n);
		generated = ((transform != null) ? transform.gameObject : UOUtility.Create(n, base.gameObject, typeof(MeshFilter), typeof(MeshRenderer), typeof(MeshBender)));
		generated.GetComponent<MeshRenderer>().material = material;
		meshBender = generated.GetComponent<MeshBender>();
		spline = GetComponent<Spline>();
		meshBender.Source = SourceMesh.Build(mesh).Rotate(Quaternion.Euler(rotation)).Scale(scale);
		meshBender.Mode = MeshBender.FillingMode.StretchToInterval;
		meshBender.SetInterval(spline, 0f, 0.01f);
	}
}
