using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace SplineMesh;

[ExecuteInEditMode]
[SelectionBase]
[DisallowMultipleComponent]
public class ExampleTrack : MonoBehaviour
{
	private GameObject generated;

	private Spline spline;

	private bool toUpdate;

	public List<TrackSegment> segments = new List<TrackSegment>();

	public bool updateInPlayMode;

	private void OnEnable()
	{
		string n = "generated by " + GetType().Name;
		Transform transform = base.transform.Find(n);
		generated = ((transform != null) ? transform.gameObject : UOUtility.Create(n, base.gameObject));
		spline = GetComponentInParent<Spline>();
		while (segments.Count < spline.nodes.Count)
		{
			segments.Add(new TrackSegment());
		}
		while (segments.Count > spline.nodes.Count)
		{
			segments.RemoveAt(segments.Count - 1);
		}
		spline.NodeListChanged += delegate(object s, ListChangedEventArgs<SplineNode> e)
		{
			switch (e.type)
			{
			case ListChangeType.Add:
				segments.Add(new TrackSegment());
				break;
			case ListChangeType.Remove:
				segments.RemoveAt(e.removeIndex);
				break;
			case ListChangeType.Insert:
				segments.Insert(e.insertIndex, new TrackSegment());
				break;
			}
			toUpdate = true;
		};
		toUpdate = true;
	}

	private void OnValidate()
	{
		if (!(spline == null))
		{
			toUpdate = true;
		}
	}

	private void Update()
	{
		if ((updateInPlayMode || !Application.isPlaying) && toUpdate)
		{
			toUpdate = false;
			CreateMeshes();
		}
	}

	public void CreateMeshes()
	{
		List<GameObject> list = new List<GameObject>();
		for (int i = 0; i < spline.GetCurves().Count; i++)
		{
			CubicBezierCurve interval = spline.GetCurves()[i];
			foreach (TransformedMesh transformedMesh in segments[i].transformedMeshes)
			{
				if (!(transformedMesh.mesh == null))
				{
					string n = "segment " + i + " mesh " + segments[i].transformedMeshes.IndexOf(transformedMesh);
					Transform transform = generated.transform.Find(n);
					GameObject gameObject;
					if (transform == null)
					{
						gameObject = UOUtility.Create(n, generated, typeof(MeshFilter), typeof(MeshRenderer), typeof(MeshBender), typeof(MeshCollider));
						gameObject.isStatic = true;
					}
					else
					{
						gameObject = transform.gameObject;
					}
					gameObject.GetComponent<MeshRenderer>().material = transformedMesh.material;
					gameObject.GetComponent<MeshCollider>().material = transformedMesh.physicMaterial;
					MeshBender component = gameObject.GetComponent<MeshBender>();
					component.Source = SourceMesh.Build(transformedMesh.mesh).Translate(transformedMesh.translation).Rotate(Quaternion.Euler(transformedMesh.rotation))
						.Scale(transformedMesh.scale);
					component.SetInterval(interval);
					component.ComputeIfNeeded();
					list.Add(gameObject);
				}
			}
		}
		foreach (GameObject item in (from Transform child in generated.transform
			select child.gameObject).Except(list))
		{
			UOUtility.Destroy(item);
		}
	}
}
