using UnityEngine;

namespace SplineMesh;

[ExecuteInEditMode]
[RequireComponent(typeof(Spline))]
public class ExampleContortAlong : MonoBehaviour
{
	private Spline spline;

	private float rate;

	private MeshBender meshBender;

	[HideInInspector]
	public GameObject generated;

	public Mesh mesh;

	public Material material;

	public Vector3 rotation;

	public Vector3 scale;

	public float DurationInSecond;

	private void OnEnable()
	{
		rate = 0f;
		Init();
	}

	private void OnDisable()
	{
	}

	private void OnValidate()
	{
		Init();
	}

	private void EditorUpdate()
	{
		rate += Time.deltaTime / DurationInSecond;
		if (rate > 1f)
		{
			rate -= 1f;
		}
		Contort();
	}

	private void Contort()
	{
		if (generated != null)
		{
			meshBender.SetInterval(spline, spline.Length * rate);
			meshBender.ComputeIfNeeded();
		}
	}

	private void Init()
	{
		string n = "generated by " + GetType().Name;
		Transform transform = base.transform.Find(n);
		generated = ((transform != null) ? transform.gameObject : UOUtility.Create(n, base.gameObject, typeof(MeshFilter), typeof(MeshRenderer), typeof(MeshBender)));
		generated.GetComponent<MeshRenderer>().material = material;
		meshBender = generated.GetComponent<MeshBender>();
		spline = GetComponent<Spline>();
		meshBender.Source = SourceMesh.Build(mesh).Rotate(Quaternion.Euler(rotation)).Scale(scale);
		meshBender.Mode = MeshBender.FillingMode.Once;
		meshBender.SetInterval(spline, 0f);
	}
}
