using UnityEngine;

namespace SplineMesh;

[ExecuteInEditMode]
[RequireComponent(typeof(Spline))]
public class ExampleFollowSpline : MonoBehaviour
{
	private GameObject generated;

	private Spline spline;

	private float rate;

	public GameObject Follower;

	public float DurationInSecond;

	private void OnEnable()
	{
		rate = 0f;
		string n = "generated by " + GetType().Name;
		Transform transform = base.transform.Find(n);
		generated = ((transform != null) ? transform.gameObject : Object.Instantiate(Follower, base.gameObject.transform));
		generated.name = n;
		spline = GetComponent<Spline>();
	}

	private void OnDisable()
	{
	}

	private void EditorUpdate()
	{
		rate += Time.deltaTime / DurationInSecond;
		if (rate > (float)(spline.nodes.Count - 1))
		{
			rate -= spline.nodes.Count - 1;
		}
		PlaceFollower();
	}

	private void PlaceFollower()
	{
		if (generated != null)
		{
			CurveSample sample = spline.GetSample(rate);
			generated.transform.localPosition = sample.location;
			generated.transform.localRotation = sample.Rotation;
		}
	}
}
