using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace SplineMesh;

[ExecuteInEditMode]
[RequireComponent(typeof(Spline))]
public class RopeBuilder : MonoBehaviour
{
	private bool toUpdate;

	private GameObject generated;

	private Spline spline;

	private GameObject firstSegment;

	[SerializeField]
	public List<GameObject> wayPoints = new List<GameObject>();

	public GameObject segmentPrefab;

	public int segmentCount;

	public float segmentSpacing;

	private GameObject Generated
	{
		get
		{
			if (generated == null)
			{
				string n = "generated by " + GetType().Name;
				Transform transform = base.transform.Find(n);
				generated = ((transform != null) ? transform.gameObject : UOUtility.Create(n, base.gameObject));
			}
			return generated;
		}
	}

	private void OnEnable()
	{
		spline = GetComponent<Spline>();
		toUpdate = true;
	}

	private void OnValidate()
	{
		toUpdate = true;
	}

	private void Update()
	{
		if (toUpdate)
		{
			toUpdate = false;
			Generate();
			UpdateSpline();
		}
		UpdateNodes();
		if (Application.isPlaying)
		{
			firstSegment.transform.localPosition = new Vector3(Mathf.Sin(Time.time) * 3f, 0f, 0f);
		}
	}

	private void UpdateNodes()
	{
		int num = 0;
		foreach (GameObject wayPoint in wayPoints)
		{
			SplineNode splineNode = spline.nodes[num++];
			if (Vector3.Distance(splineNode.Position, base.transform.InverseTransformPoint(wayPoint.transform.position)) > 0.001f)
			{
				splineNode.Position = base.transform.InverseTransformPoint(wayPoint.transform.position);
				splineNode.Up = wayPoint.transform.up;
			}
		}
	}

	private void UpdateSpline()
	{
		foreach (GameObject item in wayPoints.ToList())
		{
			if (item == null)
			{
				wayPoints.Remove(item);
			}
		}
		int count = wayPoints.Count;
		while (spline.nodes.Count < count)
		{
			spline.AddNode(new SplineNode(Vector3.zero, Vector3.zero));
		}
		while (spline.nodes.Count > count && spline.nodes.Count > 2)
		{
			spline.RemoveNode(spline.nodes.Last());
		}
	}

	private void Generate()
	{
		UOUtility.DestroyChildren(Generated);
		wayPoints.Clear();
		float num = 0f;
		Joint joint = null;
		for (int i = 0; i < segmentCount; i++)
		{
			GameObject gameObject = UOUtility.Instantiate(segmentPrefab, Generated.transform);
			gameObject.transform.Translate(0f, 0f, num);
			Rigidbody component = gameObject.GetComponent<Rigidbody>();
			if (i == 0)
			{
				firstSegment = gameObject;
				component.constraints = RigidbodyConstraints.FreezePosition;
			}
			if (joint != null)
			{
				joint.connectedBody = component;
			}
			joint = gameObject.GetComponent<Joint>();
			wayPoints.Add(gameObject);
			num += segmentSpacing;
		}
		UOUtility.Destroy(joint);
	}
}
