using System.Collections.Generic;
using UnityEngine;

namespace SplineMesh;

[ExecuteInEditMode]
[RequireComponent(typeof(Spline))]
public class SplineExtrusion : MonoBehaviour
{
	private Spline spline;

	private bool toUpdate = true;

	private GameObject generated;

	public List<ExtrusionSegment.Vertex> shapeVertices = new List<ExtrusionSegment.Vertex>();

	public Material material;

	public float textureScale = 1f;

	public float sampleSpacing = 0.1f;

	private void Reset()
	{
		shapeVertices.Clear();
		shapeVertices.Add(new ExtrusionSegment.Vertex(new Vector2(0f, 0.5f), new Vector2(0f, 1f), 0f));
		shapeVertices.Add(new ExtrusionSegment.Vertex(new Vector2(1f, -0.5f), new Vector2(1f, -1f), 0.33f));
		shapeVertices.Add(new ExtrusionSegment.Vertex(new Vector2(-1f, -0.5f), new Vector2(-1f, -1f), 0.66f));
		toUpdate = true;
		OnEnable();
	}

	private void OnValidate()
	{
		toUpdate = true;
	}

	private void OnEnable()
	{
		string n = "generated by " + GetType().Name;
		Transform transform = base.transform.Find(n);
		generated = ((transform != null) ? transform.gameObject : UOUtility.Create(n, base.gameObject));
		spline = GetComponentInParent<Spline>();
		spline.NodeListChanged += delegate
		{
			toUpdate = true;
		};
	}

	private void Update()
	{
		if (toUpdate)
		{
			GenerateMesh();
			toUpdate = false;
		}
	}

	private void GenerateMesh()
	{
		UOUtility.DestroyChildren(generated);
		int num = 0;
		float num2 = 0f;
		foreach (CubicBezierCurve curf in spline.GetCurves())
		{
			GameObject obj = UOUtility.Create("segment " + num++, generated, typeof(MeshFilter), typeof(MeshRenderer), typeof(ExtrusionSegment), typeof(MeshCollider));
			obj.GetComponent<MeshRenderer>().material = material;
			ExtrusionSegment component = obj.GetComponent<ExtrusionSegment>();
			component.ShapeVertices = shapeVertices;
			component.TextureScale = textureScale;
			component.TextureOffset = num2;
			component.SampleSpacing = sampleSpacing;
			component.SetInterval(curf);
			num2 += curf.Length;
		}
	}

	public void SetToUpdate()
	{
		toUpdate = true;
	}
}
